version: '3.1'

# Start-up
# docker-compose up

# Clean-up
# docker-compose down --volume
services:
  postgres:
    image: postgres:10.1
    container_name: genericDB
    environment:
      - "POSTGRES_DB=himama"
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
    ports:
      - "5432:5432"
    networks:
      - genericdb
networks:
  genericdb: